config/routes.rb
Rails.application.routes.draw do
  apipie
  resources :uploaders do
    collection do
      get :new_health_care
      get :new_description_template
      get :health_care_indicators_index
      get :health_care_2_0_show
      get :resources
      get :resources_index
      get :new_resources
      get :indicators_map_colors
      get :indicators_map_colors_index
      get :new_indicators_map_colors
      get :description_template_index
      get :description_template_show
    end
  end
  resources :resources

  authenticated :user do
    root to: 'uploaders#index', as: :authenticated_root
  end

  root to: redirect('/users/sign_in')

  devise_for :users

  namespace :api, defaults: {format: :json} do
    namespace :v1 do

      resources :indicators, only: [:index, :show] do
      end

      resources :partners

      get '/places', to: 'geographies#index', as: 'community_areas'
      get '/place/:geo_slug', to: 'geographies#show', as: 'community_area'
      get '/place/:geo_slug/resources(/:dataset_slug)', to: 'geographies#resources_json', as: 'community_area_resources'
      get '/place/demography/:geo_slug', to: 'geographies#show_demographic_dataset', as: 'community_area_demography'
      get '/place/insurance/:cat_id/:geo_slug', to: 'geographies#show_insurance_dataset', as: 'community_area_insurance'
      get '/place/providers/:geo_slug', to: 'geographies#show_provider_dataset', as: 'community_area_provider'
      get '/place/category/:cat_id/:geo_slug', to: 'geographies#show_category_dataset', as: 'community_area_category'
      get '/topics', to: 'topics#index', as: 'topics_list'
      get '/topic_city/:year/:indicator_slug', to: 'topics#city_show', as: 'topic_city_detail'
      get '/topic_area/:year/:indicator_slug', to: 'topics#area_show', as: 'topic_community_area_detail'
      get '/topic_demo/:indicator_slug/:demo_slug', to: 'topics#demo', as: 'topic_detail_demography'
      get '/topic_detail/:indicator_slug', to: 'topics#trend', as: 'topic_detailed_all'
      get '/topic_recent/:indicator_slug', to: 'topics#recent', as: 'topic_recent'
      get '/topic_info/:geo_slug/:indicator_slug', to: 'topics#info', as: 'topic_info'
      get '/topic_sources', to: 'topics#topic_sources', as: 'topic_sources'
      get '/resources_all(/:dataset_slug)', to: 'geographies#resources_all', as: 'resources_all'
      get '/resources_category/:category_slug(/:dataset_slug)', to: 'geographies#resources_category', as: 'chicago_resources_category'
      get '/resources(/:dataset_id)/:north/:east/:south/:west' => 'geographies#resources_json'
      get '/resources(/:dataset_id)/:community_area_slug' => 'geographies#resources_json'
      get '/hospital/:slug', to: 'hospital#show', as: 'hospital_with_slug'
      get '/:geo_slug/hospitals', to: 'hospital#index', as: 'community_area_hospitals'
      get '/:geo_slug/:category_slug/community_area_detail', to: 'geographies#community_area_detail', as: 'community_area_detail'
      get '/area_indices/:indicator_slug', to: 'geographies#area_indices', as: 'area_indices'
      get '/hospitals', to: 'hospital#hospitals_all', as: 'chicago_hospitals'
      get '/race/:area_slug', to: 'topics#race', as: 'race'
    end
  end
end

app/models/uploader.rb
class Uploader < ActiveRecord::Base
    mount_uploader :path, ItemUploader
    enum status: [:uploaded, :processing, :completed, :failed]
    has_many :resources, dependent: :destroy
    belongs_to :user

    TYPES = { default: 0, indicator_2_0: 1, description_template: 2, resources: 3, indicator_map_color: 4 }

    validates :user_id, presence: true
    validates :name, presence: true

    def initialize_state
      self.update(current_row: 0)
      self.update(total_row: 0)
    end

    def update_current_state(count)
      self.update(current_row: count)
    end

    def update_total_row(count)
      self.update(total_row: count)
    end

    def update_name(name)
      self.update(name: name)
    end

    def remove_resources
      self.resources.delete_all
    end

    def remove_health_care_indicators
      HcIndicator.delete_all
    end

    def remove_description_template
      IndicatorProperty.delete_all
    end

    def remove_intervention_location
      InterventionLocation.delete_all
    end

    def remove_indicators_map_colors
      IndicatorMapColour.delete_all
    end

    def update_indicator(id)
      self.update(indicator_id: id)
    end

end

app/controllers/uploaders_controller.rb
class UploadersController < ApplicationController
  before_action :set_uploader, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  require 'roo'

  def index
    @uploaders = Uploader.where(category: Uploader::TYPES[:default])
  end

  def health_care_2_0_show
    @uploaders = Uploader.where(category: Uploader::TYPES[:indicator_2_0])
  end

  def resources
    @uploaders = Uploader.where(category: Uploader::TYPES[:resources])
  end

  def indicators_map_colors
    @uploaders = Uploader.where(category: Uploader::TYPES[:indicator_map_color])
  end

  def health_care_indicators_index
     @uploader = Uploader.find_by_id(params[:id])
     @indicators = HcIndicator.where(uploader_id: params[:id]).paginate(:page => params[:page], :per_page => 16)
  end

  def description_template_show
    @uploaders = Uploader.where(category: Uploader::TYPES[:description_template])
  end

  def description_template_index
     @indicators = IndicatorProperty.all.paginate(:page => params[:page], :per_page => 16)
  end

  def resources_index
     @uploader = Uploader.find_by_id(params[:id])
     @resources = InterventionLocation.all.paginate(:page => params[:page], :per_page => 16)
  end

  def indicators_map_colors_index
    @uploader = Uploader.find_by_id(params[:id])
    @indicators_map_colors = IndicatorMapColour.all.paginate(:page => params[:page], :per_page => 16)
  end

  def show
     @uploader = Uploader.find(params[:id])
  end

  def new
    @previous_uploader = params[:previous_uploader] ? Uploader.find_by_id(params[:previous_uploader]) : nil
    @uploader = Uploader.new
    category = params[:category]
    if category
      @uploader.category = category
    end
  end

  def new_health_care
    @uploader = Uploader.new
    @uploader.category = Uploader::TYPES[:indicator_2_0]
    render :new
  end

  def new_description_template
    @uploader = Uploader.new
    @uploader.category = Uploader::TYPES[:description_template]
    render :new
  end

  def new_resources
    @uploader = Uploader.new
    @uploader.category = Uploader::TYPES[:resources]
    render :new
  end

  def new_indicators_map_colors
    @uploader = Uploader.new
    @uploader.category = Uploader::TYPES[:indicator_map_color]
    render :new
  end

  def edit
  end

  def create
    @uploader = current_user.uploaders.build(uploader_params)
    content_type = uploader_params[:path].original_filename.last(4)
    if (content_type.include? "csv") || (content_type.include? "xlsx")
      if @uploader.category != Uploader::TYPES[:default]
        previous_uploader = nil
      else
        previous_uploader = find_previous_uploader
      end
      if  !previous_uploader
        @uploader.update_name(uploader_params[:path].original_filename)
        @uploader.initialize_state
        respond_to do |format|
          if @uploader.save
            @uploader.uploaded!
            UploadProcessingWorker.perform_async(@uploader.id)
            if @uploader.category != Uploader::TYPES[:resources]
              format.html { redirect_to root_path, notice: 'File successfully uploaded.' }
              format.json { render :show, status: :created, location: @uploader }
            else
              format.html { redirect_to resources_uploaders_path, notice: 'File successfully uploaded.' }
              format.json { render :show, status: :created, location: @uploader }
            end
          else
            format.html { render :new }
            format.json { render json: @uploader.errors, status: :unprocessable_entity }
          end
        end
      else
        redirect_to new_uploader_path(previous_uploader: previous_uploader, category: @uploader.category)
      end
    else
     redirect_to new_uploader_path(category: @uploader.category)
    end
  end

  def update
    case @uploader.category
      when Uploader::TYPES[:default]
        @uploader.remove_resources
        Indicator.find(@uploader.indicator_id).destroy
      when Uploader::TYPES[:indicator_2_0]
        @uploader.remove_health_care_indicators
    end
    @uploader.update_name(uploader_params[:path].original_filename)
    @uploader.initialize_state
    respond_to do |format|
      if @uploader.update(uploader_params)
        @uploader.uploaded!
        UploadProcessingWorker.perform_async(@uploader.id)
        if @uploader.category != Uploader::TYPES[:resources]
          format.html { redirect_to root_path, notice: 'File successfully updated.' }
          format.json { render :show, status: :ok, location: @uploader }
        else
          format.html { redirect_to resources_uploaders_path, notice: 'File successfully uploaded.' }
          format.json { render :show, status: :created, location: @uploader }
        end
      else
        format.html { render :edit  }
        format.json { render json: @uploader.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_health_care_indicators
    @uploader.remove_health_care_indicators
    @uploader.update_name(uploader_params[:path].original_filename)
    @uploader.initialize_state
    respond_to do |format|
      if @uploader.update(uploader_params)
        @uploader.uploaded!
        UploadProcessingWorker.perform_async(@uploader.id)
        format.html { redirect_to root_path, notice: 'File successfully updated.' }
        format.json { render :show, status: :ok, location: @uploader }
      else
        format.html { render :edit  }
        format.json { render json: @uploader.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    current_indicator = Indicator.find_by_id(@uploader.indicator_id)
    if @uploader.category == Uploader::TYPES[:indicator_2_0]
      @uploader.remove_health_care_indicators
    elsif @uploader.category == Uploader::TYPES[:description_template]
      @uploader.remove_description_template
    elsif @uploader.category == Uploader::TYPES[:resources]
      @uploader.remove_intervention_location
    elsif @uploader.category == Uploader::TYPES[:indicator_map_color]
      @uploader.remove_indicators_map_colors
    end

    @uploader.destroy
    current_indicator.destroy if current_indicator
    respond_to do |format|
      format.html { redirect_to uploaders_url, notice: 'Uploader was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_uploader
      @uploader = Uploader.find(params[:id])
    end

    def uploader_params
      params.require(:uploader).permit(:path, :comment, :category)
    end

    def find_previous_uploader
      previous_uploader = nil
      if file = Roo::Spreadsheet.open(uploader_params[:path].path)
        total_count = file.last_row - 1
        if total_count > 1
          2.upto 2 do |row|
            indicator_name = file.cell(row, 'C').to_s
            indicator_slug  = CGI.escape(indicator_name.tr(' ', '-').tr('/', '-').tr(',', '-').downcase)
            if indicator = Indicator.find_by_slug(indicator_slug)
              previous_uploader = Uploader.find_by_indicator_id(indicator.id)
            end
          end
        end
      end
      previous_uploader
    end
end

app/helpers/uploaders_helper.rb
module UploadersHelper
end

app/views/uploaders/_edit_form.html.erb
<%= form_for(@uploader) do |f| %>
  <% if @uploader.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@uploader.errors.count, "error") %> prohibited this uploader from being saved:</h2>

      <ul>
      <% @uploader.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :path %><br>
    <%= f.file_field :path %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uploaders/description_template_index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Description Template</h1>
<%= link_to 'Replace file', edit_uploader_path(@uploader), class: 'btn btn-primary btn-xs', remote: true if @uploader %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Indicator Name</th>
      <th>Indicator Slug</th>
      <th>Description</th>
      <th>Order</th>
    </tr>
  </thead>

  <tbody>
    <% @indicators.each do |indicator| %>
      <tr>
        <td><%= indicator.id %></td>
        <td><%= indicator.name %></td>
        <td><%= indicator.slug %></td>
        <td><%= indicator.description %></td>
        <td><%= indicator.order %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= will_paginate @indicators %>
<br>
<%= link_to 'View Uploaders', description_template_show_uploaders_path, :class => "btn-custom"%>

app/views/uploaders/edit.html.erb
<h1>Editing Uploader</h1>
<%= render 'edit_form' %>
<%= link_to 'Show', @uploader %> |
<%= link_to 'Back', uploaders_path %>

app/views/uploaders/edit.js.erb
$('<%= j render "form", title: "Edit file upload" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/uploaders/health_care_indicators_index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Data View Health Care 2.0</h1>
<%= link_to 'Replace file', edit_uploader_path(@uploader), class: 'btn btn-primary btn-xs', remote: true if @uploader %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Uploader_id</th>
      <th>Indicator</th>
      <th>Category</th>
      <th>Most Recent Year</th>
      <th>Priority Population</th>
      <th>Priority Population Most Recent Year</th>
      <th>2020 Target</th>
      <th>Datasource</th>
    </tr>
  </thead>

  <tbody>
    <% @indicators.each do |indicator| %>
      <tr>
        <td><%= indicator.id %></td>
        <td><%= indicator.uploader_id %></td>
        <td><%= indicator.name %></td>
        <td><%= indicator.category %></td>
        <td><%= indicator.most_recent_year %></td>
        <td><%= indicator.priority_population %></td>
        <td><%= indicator.priority_population_most_recent_year %></td>
        <td><%= indicator.target %></td>
        <td><a href="<%= indicator.datasource_url %>" target='_blank'><%= indicator.datasource %></a></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= will_paginate @indicators %>
<br>
<%= link_to 'View Uploaders', uploaders_path, :class => "btn-custom"%>

app/views/uploaders/index.html.erb
<div class="container">
  <div class="col-xs-12">
    <% if @hc_uploaders.count > 0 %>
      <br>
      <h1>Listing Health Care 2.0 Indicators
        <a  onClick="window.location.reload()" class="btn btn-primary btn-sm">
          refresh <i class="fa fa-refresh" aria-hidden="true"></i>
        </a>
      </h1>
      <p class="lead">This is the full list of health care 2.0 indicators that are in the system</p>
      <br>
      <table class="table table-striped table-hover uploaders">
        <thead>
        <tr>
          <!-- <th>Id</th> -->
          <th>File</th>
          <th>Status</th>
          <th>Total</th>
          <th>Processed</th>
          <!-- <th>Show</th> -->
          <th><!--View--></th>
          <th><!--Edit--></th>
          <th><!--Destroy--></th>
        </tr>
        </thead>

        <tbody>
        <% @hc_uploaders.each do |uploader| %>
          <tr>
            <!-- <td><%= uploader.id %></td> -->
            <td>
              <a class="btn btn-primary btn-sm" href="<%= uploader.path %>">
                <%= uploader.name %>
                <i class="fa fa-download" aria-hidden="true"></i>
              </a>
            </td>
            <td><%= uploader.status %></td>
            <td><%= uploader.total_row %></td>
            <td><%= uploader.current_row %></td>
            <!-- <td><%= link_to 'Show', uploader_path(uploader) %></td> -->
            <td><%= link_to 'View Data', health_care_indicators_index_uploaders_path(id: uploader.id), class: 'btn btn-primary btn-xs'  %></td>
            <td><%= link_to 'Replace', edit_uploader_path(uploader), class: 'btn btn-primary btn-xs', remote: true %></td>
            <td><%= link_to '<i class="glyphicon glyphicon-remove-circle"></i>'.html_safe, uploader, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <br>
    <% else %>
      <h1>Add your First Health Care 2.0 Indicator File</h1>
      <br>
    <% end %>
    <% if @hc_uploaders.count == 0 %>
      <%= link_to "Upload New HC 2.0 File <i class='fa fa-2 fa-cloud-upload' aria-hidden='true'></i>".html_safe , new_health_care_uploaders_path, remote: true, class: "btn-custom" %>
    <% end %>
  </div>
  <div class="col-xs-12">
    <% if @uploaders.count > 0 %>
    <br>
    <h1>Listing Indicators
      <a  onClick="window.location.reload()" class="btn btn-primary btn-sm">
        refresh <i class="fa fa-refresh" aria-hidden="true"></i>
      </a>
    </h1>
    <p class="lead">This is the full list of indicators that are in the system</p>
    <br>
    <table class="table table-striped table-hover uploaders">
      <thead>
        <tr>
          <!-- <th>Id</th> -->
          <th>File</th>
          <th>Status</th>
          <th>Total</th>
          <th>Processed</th>
          <!-- <th>Show</th> -->
          <th><!--View--></th>
          <th><!--Edit--></th>
          <th><!--Destroy--></th>
        </tr>
      </thead>

      <tbody>
        <% @uploaders.each do |uploader| %>
          <tr>
            <!-- <td><%= uploader.id %></td> -->
            <td>
              <a class="btn btn-primary btn-sm" href="<%= uploader.path %>">
                <%= uploader.name %>
                <i class="fa fa-download" aria-hidden="true"></i>
              </a>
            </td>
            <td><%= uploader.status %></td>
            <td><%= uploader.total_row %></td>
            <td><%= uploader.current_row %></td>
            <!-- <td><%= link_to 'Show', uploader_path(uploader) %></td> -->
            <td><%= link_to 'View Data', resource_path(uploader.id), class: 'btn btn-primary btn-xs'  %></td>
            <td><%= link_to 'Replace', edit_uploader_path(uploader), class: 'btn btn-primary btn-xs', remote: true %></td>
            <td><%= link_to '<i class="glyphicon glyphicon-remove-circle"></i>'.html_safe, uploader, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <% else %>
    <h1>Add your First Indicator File</h1>
    <br>
    <% end %>

    <%= link_to "Upload New File <i class='fa fa-2 fa-cloud-upload' aria-hidden='true'></i>".html_safe , new_uploader_path, remote: true, class: "btn-custom" %>
  </div>
</div>

app/views/uploaders/indicators_map_colors.html.erb
<div class="container">
  <div class="col-xs-12">
    <% if @uploaders.count > 0 %>
    <br>
    <h1>Indicators Map Colors
      <a onClick="window.location.reload()" class="btn btn-primary btn-sm">
        refresh <i class="fa fa-refresh" aria-hidden="true"></i>
      </a>
    </h1>
    <br>
    <table class="table table-striped table-hover uploaders">
      <thead>
        <tr>
          <th>File</th>
          <th>Status</th>
          <th>Total</th>
          <th>Processed</th>
        </tr>
      </thead>

      <tbody>
        <% @uploaders.each do |uploader| %>
          <tr>
            <td>
              <a class="btn btn-primary btn-sm" href="<%= uploader.path %>">
                <%= uploader.name %>
                <i class="fa fa-download" aria-hidden="true"></i>
              </a>
            </td>
            <td><%= uploader.status %></td>
            <td><%= uploader.total_row %></td>
            <td><%= uploader.current_row %></td>
            <td><%= link_to 'View Data', indicators_map_colors_index_uploaders_path(id: uploader.id), class: 'btn btn-primary btn-xs'  %></td>
            <td><%= link_to 'Replace', edit_uploader_path(uploader), class: 'btn btn-primary btn-xs', remote: true %></td>
            <td><%= link_to '<i class="glyphicon glyphicon-remove-circle"></i>'.html_safe, uploader, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <% else %>
    <h1>Add your Indicators Map Colors File</h1>
    <br>
      <%= link_to "Upload New File <i class='fa fa-2 fa-cloud-upload' aria-hidden='true'></i>".html_safe , new_indicators_map_colors_uploaders_path, remote: true, class: "btn-custom" %>
    <% end %>
  </div>
</div>

app/views/uploaders/indicators_map_colors_index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Data View Indicators Map Colors</h1>
<%= link_to 'Replace file', edit_uploader_path(@uploader), class: 'btn btn-primary btn-xs', remote: true if @uploader %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Indicator Name</th>
      <th>Indicator Slug</th>
      <th>Year</th>
      <th>Type</th>
      <th>Range Start</th>
      <th>Range End</th>
      <th>Color</th>
    </tr>
  </thead>

  <tbody>
    <% @indicators_map_colors.each do |indicator_map_color| %>
      <tr>
        <td><%= indicator_map_color.id %></td>
        <td><%= indicator_map_color.name %></td>
        <td><%= indicator_map_color.slug %></td>
        <td><%= indicator_map_color.year %></td>
        <td><%= indicator_map_color.map_key %></td>
        <td><%= indicator_map_color.start_value %></td>
        <td><%= indicator_map_color.end_value %></td>
        <td><%= indicator_map_color.colour %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= will_paginate @indicators_map_colors %>
<br>
<%= link_to 'View Uploaders', uploaders_path, :class => "btn-custom"%>

app/views/uploaders/new.html.erb
<% if @uploader.category == Uploader::TYPES[:indicator_2_0] %>
  <h1>Upload New HC 2.0 File </h1>
<% else %>
  <h1>New Uploader</h1>
<% end %>
<%= render 'form_new' %>

<%= link_to 'Back', uploaders_path %>

app/views/uploaders/new.js.erb
$('<%= j render "form", title: "New file upload" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/uploaders/resources.html.erb
<div class="container">
  <div class="col-xs-12">
    <% if @uploaders.count > 0 %>
    <br>
    <h1>Resource
      <a  onClick="window.location.reload()" class="btn btn-primary btn-sm">
        refresh <i class="fa fa-refresh" aria-hidden="true"></i>
      </a>
    </h1>
    <br>
    <table class="table table-striped table-hover uploaders">
      <thead>
        <tr>
          <!-- <th>Id</th> -->
          <th>File</th>
          <th>Status</th>
          <th>Total</th>
          <th>Processed</th>
          <!-- <th>Show</th> -->
          <th><!--View--></th>
          <th><!--Edit--></th>
          <th><!--Destroy--></th>
        </tr>
      </thead>

      <tbody>
        <% @uploaders.each do |uploader| %>
          <tr>
            <!-- <td><%= uploader.id %></td> -->
            <td>
              <a class="btn btn-primary btn-sm" href="<%= uploader.path %>">
                <%= uploader.name %>
                <i class="fa fa-download" aria-hidden="true"></i>
              </a>
            </td>
            <td><%= uploader.status %></td>
            <td><%= uploader.total_row %></td>
            <td><%= uploader.current_row %></td>
            <td><%= link_to 'View Data', resources_index_uploaders_path(id: uploader.id), class: 'btn btn-primary btn-xs'  %></td>
            <td><%= link_to 'Replace', edit_uploader_path(uploader), class: 'btn btn-primary btn-xs', remote: true %></td>
            <td><%= link_to '<i class="glyphicon glyphicon-remove-circle"></i>'.html_safe, uploader, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <% else %>
    <h1>Add your First Maps Corps File</h1>
    <br>
      <%= link_to "Upload New File <i class='fa fa-2 fa-cloud-upload' aria-hidden='true'></i>".html_safe , new_resources_uploaders_path, remote: true, class: "btn-custom" %>
    <% end %>
  </div>
</div>

app/views/uploaders/resources_index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Data View Resources</h1>
<%= link_to 'Replace file', edit_uploader_path(@uploader), class: 'btn btn-primary btn-xs', remote: true if @uploader %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>Zip Code</th>
      <th>Community Area</th>
      <th>Categories</th>
      <th>Phone</th>
      <th>Program URL</th>
      <th>Latitude</th>
      <th>Longitude</th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.id %></td>
        <td><%= resource.program_name %></td>
        <td><%= resource.address %></td>
        <td><%= resource.city %></td>
        <td><%= resource.zip %></td>
        <td><%= resource.community_area_name %></td>
        <td><%= resource.categories %></td>
        <td><%= resource.phone %></td>
        <td><a href="<%= resource.program_url %>" target='_blank'><%= resource.program_url != "NULL" ? resource.program_url : nil %></a></td>
        <td><%= resource.latitude %></td>
        <td><%= resource.longitude %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= will_paginate @resources %>
<br>
<%= link_to 'View Uploaders', uploaders_path, :class => "btn-custom"%>

app/views/uploaders/show.html.erb
<p><%= @uploader.id %></p>
<p><a href="<%= @uploader.path %>"><%= @uploader.name %></a></p>
<p><%= @uploader.comment %></a></p>
<%= link_to 'Edit', edit_uploader_path(@uploader) %> |
<%= link_to 'Back', uploaders_path %>