config/routes.rb
Rails.application.routes.draw do
  apipie
  resources :uploaders do
    collection do
      get :new_health_care
      get :new_description_template
      get :health_care_indicators_index
      get :health_care_2_0_show
      get :resources
      get :resources_index
      get :new_resources
      get :indicators_map_colors
      get :indicators_map_colors_index
      get :new_indicators_map_colors
      get :description_template_index
      get :description_template_show
    end
  end
  resources :resources

  authenticated :user do
    root to: 'uploaders#index', as: :authenticated_root
  end

  root to: redirect('/users/sign_in')

  devise_for :users

  namespace :api, defaults: {format: :json} do
    namespace :v1 do

      resources :indicators, only: [:index, :show] do
      end

      resources :partners

      get '/places', to: 'geographies#index', as: 'community_areas'
      get '/place/:geo_slug', to: 'geographies#show', as: 'community_area'
      get '/place/:geo_slug/resources(/:dataset_slug)', to: 'geographies#resources_json', as: 'community_area_resources'
      get '/place/demography/:geo_slug', to: 'geographies#show_demographic_dataset', as: 'community_area_demography'
      get '/place/insurance/:cat_id/:geo_slug', to: 'geographies#show_insurance_dataset', as: 'community_area_insurance'
      get '/place/providers/:geo_slug', to: 'geographies#show_provider_dataset', as: 'community_area_provider'
      get '/place/category/:cat_id/:geo_slug', to: 'geographies#show_category_dataset', as: 'community_area_category'
      get '/topics', to: 'topics#index', as: 'topics_list'
      get '/topic_city/:year/:indicator_slug', to: 'topics#city_show', as: 'topic_city_detail'
      get '/topic_area/:year/:indicator_slug', to: 'topics#area_show', as: 'topic_community_area_detail'
      get '/topic_demo/:indicator_slug/:demo_slug', to: 'topics#demo', as: 'topic_detail_demography'
      get '/topic_detail/:indicator_slug', to: 'topics#trend', as: 'topic_detailed_all'
      get '/topic_recent/:indicator_slug', to: 'topics#recent', as: 'topic_recent'
      get '/topic_info/:geo_slug/:indicator_slug', to: 'topics#info', as: 'topic_info'
      get '/topic_sources', to: 'topics#topic_sources', as: 'topic_sources'
      get '/resources_all(/:dataset_slug)', to: 'geographies#resources_all', as: 'resources_all'
      get '/resources_category/:category_slug(/:dataset_slug)', to: 'geographies#resources_category', as: 'chicago_resources_category'
      get '/resources(/:dataset_id)/:north/:east/:south/:west' => 'geographies#resources_json'
      get '/resources(/:dataset_id)/:community_area_slug' => 'geographies#resources_json'
      get '/hospital/:slug', to: 'hospital#show', as: 'hospital_with_slug'
      get '/:geo_slug/hospitals', to: 'hospital#index', as: 'community_area_hospitals'
      get '/:geo_slug/:category_slug/community_area_detail', to: 'geographies#community_area_detail', as: 'community_area_detail'
      get '/area_indices/:indicator_slug', to: 'geographies#area_indices', as: 'area_indices'
      get '/hospitals', to: 'hospital#hospitals_all', as: 'chicago_hospitals'
      get '/race/:area_slug', to: 'topics#race', as: 'race'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_map_category.html.haml
- cat_datasets = get_dataset(category.id)

.accordion-group
  - if cat_datasets.length == 1
    - d = cat_datasets.first
    .accordion-heading
      %a.accordion-toggle{:href => "/map/#{d.slug}", :style => "color: #{link_color}"}
        = d.name
  - else
    .accordion-heading
      %a.accordion-toggle{"data-parent" => accordion_name, "data-toggle" => "collapse", :href => "#category_#{category.id}", "data-view" => category.name, :style => "color: #{link_color}"}
        - if (not @current_category.nil? and @current_category.id == category.id)
          %i.fa.fa-minus-circle.plus-minus
        - else
          %i.fa.fa-plus-circle.plus-minus
        = category.name
    .accordion-body.collapse{:id => "category_#{category.id}", :class => (not @current_category.nil? and @current_category.id == category.id) ? 'in' : ''}
      .accordion-inner{:id => "category_inner_#{category.id}"}
        %div.map-stat-select
          - cat_datasets.each do |d|
            - if d.slug == params[:dataset_slug]
              %a.btn.btn-primary.btn-mini
                %i.fa.fa-check
                = d.name
            - else
              %a.btn.btn-default.btn-mini{:href => "/map/#{d.slug}"} 
                = d.name

app/views/home/about.html.haml
- title 'About'
.row-fluid
  .span12
    %h1 About

    %p
      %a.pull-right{:href => 'http://www.smartchicagocollaborative.org'}
        %img(src="/assets/logo_smartchicago.png")
      The Chicago Health Atlas is a Web site for displaying aggregate health-related information on a map so that people can see the prevalence of specific health conditions in their area and find out how they can improve their health. 

    %p
      The 
      %a{:href => 'http://www.smartchicagocollaborative.org'}Smart Chicago Collabrative 
      is working with the 
      %a{:href => 'http://www.cityofchicago.org/city/en/depts/cdph.html'} Chicago Department of Public Health 
      and five local hospitals through 
      %a{:href => 'http://chitrec.org/'} Chicago Health Information Technology Regional Extension (CHITREC) 
      to 
      %a{:href => 'http://www.cityofchicago.org/city/en/depts/cdph/provdrs/pol_plan_report/svcs/office_of_epidemiologydataanalysisrequests.html?cq_ck=1338570736462'} visualize statistics related to public health 
      along with anonymized diagnoses, medications, and laboratory tests as provided by local healthcare institutions. The project is funded by the 
      = succeed '.' do
        %a{:href => 'http://www.spragueinstitute.org/'} Otho S. A. Sprague Memorial Institute
    %hr
    %h3#about-the-data About the data

    %p
      We currently have three types of data on the Health Atlas:

    %ol
      %li
        = succeed '.' do
          %a{:href => 'http://www.cityofchicago.org/city/en/depts/cdph/provdrs/pol_plan_report/svcs/office_of_epidemiologydataanalysisrequests.html'} Statistics related to public health in Chicago
        We obtain this information from the 
        = succeed '.' do
          %a{:href => 'http://www.cityofchicago.org/city/en/depts/cdph/provdrs/pol_plan_report/svcs/office_of_epidemiologydataanalysisrequests.html'}City of Chicago’s Open Data Portal
        The data is provided by the Chicago Department of Public Health's Epidemiology & Public Health Informatics Program
      %li
        %a{:href => 'https://github.com/smartchicago/chicago-atlas/blob/master/db/import/chitrec_data_2006-2012.csv'} Anonymized clinical diagnosis information 
        provided by CHITREC and its partners. Details on this data was presented at the 
        = succeed '.' do
          %a{:href => 'http://www.amia.org/amia2012/theater-style-demonstration'} American Medical Informatics Association (AMIA) National Symposium here in Chicago on November 6
        See the 
        = succeed '.' do
          %a{:href => 'http://www.smartchicagocollaborative.org/projects/chicago-health-atlas/'} Smart Chicago project page for a description of that talk
      %li
        <a href='http://purplebinder.com/developers'>Data about clinics, programs, and other resources</a> that can be of use to people who want to improve their health. This data is provided by <a href='http://purplebinder.com/'>Purple Binder</a>, a Chicago-based company providing a directory of social services providers and software to connect patients with the resources they need for better outcomes in health and life.
    %p
      All of the data on the Health Atlas is available for download. Downloads are in the form of CSVs, excel files, or JSON (JavaScript Object Notation). JSON is a lightweight, JavaScript-based data format that is easy to read and write. JSON is a convenient format for data sharing because it's easy for computers to parse and generate - especially in Ruby, the programming language that Chicago Health Atlas is built on.
    %p
      %b NOTE:
      This site provides applications using data that has been modified for use from its original source, 
      = succeed ',' do
        %a{:href => 'https://www.cityofchicago.org'} www.cityofchicago.org
      the official website of the City of Chicago. The City of Chicago makes no claims as to the content, accuracy, timeliness, or completeness of any of the data provided at this site. The data provided at this site is subject to change at any time. It is understood that the data provided at this site is being used at one’s own risk.
    %h3#contact-us Contact us

    %p
      Do you have data to share, questions about our work, or just want to hear more? Contact Daniel X. O'Neil at (773) 960-6045 or 
      %a{:href => 'mailto:doneil@cct.org'} doneil@cct.org 
      today.

app/views/home/index.html.erb
<div class="col-md-12">
  <div class="profile-content">
    <h2> Welcome, </h2>
    <p> This is the administrator Panel for the Atlas</p>
    <%= link_to 'View Resources', resources_path, :class => "btn-custom"%>
  </div>
</div>

app/views/home/index.html.haml
.row-fluid
  .span12
    %h1.text-center.intro
      Chicago Health Atlas
    %p.lead.text-center
      The Chicago Health Atlas is a place where you can view citywide information about health trends and take action near you to improve your own health.

.row-fluid
  .span4
    %a(href="map")
      %img.img-polaroid(src="/assets/home_city.png"alt="Citywide data")
    %p
      View 
      %a{:href => 'map'}citywide data 
      to get big-picture views of health outcomes in Chicago.
  .span4
    %a(href="places")
      %img.img-polaroid(src="/assets/home_neighborhood.png"alt="Neighborhood level data")
    %p
      Browse your 
      %a{:href => 'places'}neighborhood or zip code 
      for specific conditions and info near you. 
  .span4
    %a(href="map/affordable_resources")
      %img.img-polaroid(src="/assets/home_location.png"alt="Locations")
    %p
      Find 
      %a{:href => 'map/affordable_resources'} resources 
      where you can improve your own health, right in your own neighborhood.

.row-fluid
  %h3
    To get started, 
    %a{:href => 'map'} browse the map
    or 
    = succeed '.' do
      %a{:href => 'places'} choose a location

.row-fluid
  .span12
    %h2
      Partners
    %p
      This project is the result of many partners working to present data and analysis about health in Chicago. Learn more  
      %a{:href => 'about'}about us
      and our 
      = succeed '.' do
        %a{:href => 'partners'}partners
      If you are a health data provider and would like to take part in this project, please view our
      %a{:href => '/partner_sign_up'} partner sign up form
      to get in touch. <b>Questions?</b> 
      %a{:href => 'mailto:kwilliams@cct.org'}Contact Kyla Williams
      of the 
      = succeed '.' do
        %a{:href => 'http://www.smartchicagocollaborative.org'}Smart Chicago Collabrative

app/views/home/map.html.haml
- content_for :javascripts do
  = javascript_include_tag "leaflet"
  = javascript_include_tag "leaflet.label"
  = javascript_include_tag "jquery-ui-slider.min"
  = javascript_include_tag "jquery.address.min"
  = javascript_include_tag "jenks"

  :javascript
    $(window).resize(function () {
      var h = $(window).height(),
      offsetTop = 100; // Calculate the top offset
      $('#map').css('height', (h - offsetTop));
    }).resize();
    // hiding and modifying elements to give the map more room
    $('#container-primary').attr("class", "container-fluid");
    $('.footer').hide();
    
    $('.accordion-group').on('show.bs.collapse', function () {
      $(this).find('.plus-minus').attr('class', 'fa fa-minus-circle plus-minus')
    })
    
    $('.accordion-group').on('hide.bs.collapse', function () {
      $(this).find('.plus-minus').attr('class', 'fa fa-plus-circle plus-minus')
    })
    
    // initialize the map
    var map = L.map('map', {scrollWheelZoom:false}).setView([41.86, -87.70], 11);
    
    var mapbox = L.tileLayer('https://{s}.tiles.mapbox.com/v3/smartchicagocollaborative.heooddo8/{z}/{x}/{y}.png', {attribution: '<a href="http://www.mapbox.com/about/maps/" target="_blank">Terms &amp; Feedback</a>'}).addTo(map);
    map.attributionControl.setPrefix('');
    
    var geojsonFeature = #{@display_geojson};
    var geojson;
    var allLayers = [];
    
    // control that shows info on hover
    var info = L.control();
    
    info.onAdd = function (map) {
        this._div = L.DomUtil.create('div', 'info');
        this.update();
        return this._div;
    };
    
    function resetHighlight(e) {
        geojson.resetStyle(e.target);
    }
    
    function highlightFeature(e) {
        console.log(1);
        var layer = e.target;
        
        layer.setStyle({
            weight: 5,
            color: '#666',
            dashArray: '',
            fillOpacity: 0.7
        });
        
        if (!L.Browser.ie && !L.Browser.opera) {
            layer.bringToFront();
        }
    }

  - if @landing
    :javascript
        // plain map with no data or colors
        geojson = L.geoJson(geojsonFeature, {
            style: style,
            onEachFeature: onEachFeature
        }).addTo(map);
                
        for(layer in allLayers){
            var props = allLayers[layer].feature.properties;
            allLayers[layer].bindLabel( '<h4>' + props.name + '</h4>');
        }
        
        function style(feature) {
            return {
                fillColor: '#6BAED6',
                weight: 2,
                opacity: 1,
                color: 'white',
                dashArray: '3',
                fillOpacity: 0.7
            };
        }
        
        function onEachFeature(feature, layer) {
            layer.on({
                mouseover: highlightFeature,
                mouseout: resetHighlight,
                click: linkToDetail
            });
            allLayers.push(layer);
        }
        
        function linkToDetail(e) {
            window.location = '/place/' + e.target.feature.properties.slug + '#{@detail_url_fragment}';
        }

  - else
    :javascript
        // map with data
        var jenks_cutoffs = jenks(#{@current_statistics}, 4);
        jenks_cutoffs[0] = 0; // ensure the bottom value is 0
        jenks_cutoffs.pop(); // last item is the max value, so dont use it
        var map_colors = #{@map_colors}
        
        // get color depending on condition_title
        function getColor(d) {
            return  d >= jenks_cutoffs[3] ? map_colors[0] : 
                    d >= jenks_cutoffs[2] ? map_colors[1] : 
                    d >= jenks_cutoffs[1] ? map_colors[2] : 
                    d >= jenks_cutoffs[0] ? map_colors[3] :  
                                            map_colors[4];
        }
        
        function style(feature) {
            return {
                fillColor: getColor(feature.properties.condition_value[active_year]),
                weight: 2,
                opacity: 1,
                color: 'white',
                dashArray: '3',
                fillOpacity: 0.7
            };
        }
        
        function onEachFeature(feature, layer) {
            layer.on({
                mouseover: highlightFeature,
                mouseout: resetHighlight,
                click: linkToDetail
            });
            allLayers.push(layer);
        }
        
        function linkToDetail(e) {
            window.location = '/place/' + e.target.feature.properties.slug + '##{@current_dataset_slug}';
        }
        
        geojson = L.geoJson(geojsonFeature, {
            style: style,
            onEachFeature: onEachFeature
        }).addTo(map);
        
        var percentSuffix = '';
        if (allLayers[0].feature.properties.stat_type.indexOf("percent") !== -1) percentSuffix = '%';
        
        function update_year(year){
            active_year = year;
            $.address.parameter('year', active_year);
            var year_range = allLayers[0].feature.properties.condition_year_range;
            if (year_range != '')
                $("#year_label").text(year_range);
            else
        	    $("#year_label").text(year);
            
            for(layer in allLayers){
                var props = allLayers[layer].feature.properties;
                allLayers[layer].bindLabel( '<h4>' + props.name + '</h4>' + props.condition_title + ': ' + props.condition_value[ year ] + percentSuffix);
                allLayers[layer].setStyle({fillColor: getColor(props.condition_value[year])});
            }
        }
        
        var start_year = #{@current_dataset_start_year};
        var end_year = #{@current_dataset_end_year};
        
        $('#start_year').html(start_year);
        $('#end_year').html(end_year);
        
        if(start_year == end_year){
          // only one year in system - remove slider
          $("#slider, #start_year, #end_year").css({
            display: "none"
          });
        }
        
        var active_year = end_year;
        if ($.address.parameter('year') != null)
            active_year = $.address.parameter('year');
        
        update_year(active_year);
        
        $("#slider").slider({
          min: start_year,
          max: end_year,
          step: 1,
          value: active_year,
          slide: function(event, ui){
            update_year(ui.value);
          },
          change: function(event, ui){
            update_year(ui.value);
          },
          range: "min"
        });
        
        var legend = L.control({position: 'topright'});
        
        legend.onAdd = function (map) {
          
            var div = L.DomUtil.create('div', 'info legend'),
                grades = jenks_cutoffs,
                labels = [],
                from, to;
                
            for (var i = 0; i < grades.length; i++) {
                from = grades[i];
                to = grades[i + 1];
                
                labels.push(
                    '<i style="background:' + getColor(from + 0.01) + '"></i> ' +
                    from + (to ? '&ndash;' + to + percentSuffix : percentSuffix + '+'));
            }
            
            div.innerHTML = "<strong>#{@current_dataset_name}</strong><br>" + labels.join('<br>');
            return div;
        };
        
        legend.addTo(map);
        
        $.address.externalChange(function(event) {
            update_year($.address.parameter('year'));
            $('#slider').slider('value', $.address.parameter('year'));
        });

.row-fluid
  .span5
    %h2 Chicago Statistics

    #map_sidebar

      %h4 Conditions
      #view_accordion.accordion
        - @condition_categories.each do |c|
          = render :partial => "home/map_category", :locals => {:accordion_name => 'view_accordion', :category => c, :link_color => GlobalConstants::BLUES.first}

      %h4 Resources
      #resources_accordion.accordion
        .accordion-group
          .accordion-heading
            %a.accordion-toggle{:href => "/map/affordable_resources", :style => "color: #{GlobalConstants::ORANGES.second}"} Affordable resources

      %h4 Health Insurance
      #insurance_accordion.accordion
        - @uninsured_categories.each do |c|
          = render :partial => "home/map_category", :locals => {:accordion_name => 'insurance_accordion', :category => c, :link_color => GlobalConstants::GREENS.first}

      %h4 Hospital Admissions
      #hosp_admission_accordion.accordion
        - @hosp_admissions_categories.each do |c|
          = render :partial => "home/map_category", :locals => {:accordion_name => 'hosp_admission_accordion', :category => c, :link_color => GlobalConstants::BLUES.first}

      %h4 Other
      #stats_accordion.accordion
        = render :partial => "home/map_category", :locals => {:accordion_name => 'stats_accordion', :category => Category.find_by_name("Demographics"), :link_color => GlobalConstants::REDS.first}
        = render :partial => "home/map_category", :locals => {:accordion_name => 'stats_accordion', :category => Category.find_by_name("Healthcare Providers"), :link_color => GlobalConstants::PURPLES.first}
        = render :partial => "home/map_category", :locals => {:accordion_name => 'stats_accordion', :category => Category.find_by_name("Dentists"), :link_color => GlobalConstants::ORANGES.third}


  .span7
    %br
    #map_sidebar_header
      - if @landing
        - title 'Browse by neighborhood'
        %h4
          Select a dataset to visualize it on the map.<br>
        %small
          Examples: <a href='/map/births_birth_rate'>birth rate</a>, <a href='/map/crime_aggravated_assault'>aggravated battery</a>, or <a href='/map/infectious_disease_tuberculosis'>tuberculosis</a>.
        
      - else
        - title 'Browse ' + @current_dataset_name
        %h4
          #{@current_dataset_name}
          %small#year_label
        .span10{ :style => "margin-left: 0"}
          %div{ :id => "slider" }
          %strong.pull-left#start_year
          %strong.pull-right#end_year
        .clearfix
        %p 
          %small #{@current_dataset_description}
          - if @current_dataset_url != ''
            = raw(render_source_links(@current_dataset_provider, @current_dataset_url, @current_dataset_slug+".csv", true))
        
    %br
    #map
  

app/views/home/partner_sign_up.html.haml
- title 'Partner sign up'
.row-fluid
  .span12
    %h2 Partner sign up

    %p
      If you are a health data provider and would like to take part in this project, please complete the form below and we will contact you right away!

    #wufoo-x7x0k1
      Fill out my <a href="http://smartchicago2012.wufoo.com/forms/x7x0k1">online form</a>.

    <script type="text/javascript">var x7x0k1;(function(d, t) {
    var s = d.createElement(t), options = {
    'userName':'smartchicago2012', 
    'formHash':'x7x0k1', 
    'autoResize':true,
    'height':'666',
    'async':true,
    'header':'hide', 
    'ssl':true};
    s.src = ('https:' == d.location.protocol ? 'https://' : 'http://') + 'wufoo.com/scripts/embed/form.js';
    s.onload = s.onreadystatechange = function() {
    var rs = this.readyState; if (rs) if (rs != 'complete') if (rs != 'loaded') return;
    try { x7x0k1 = new WufooForm();x7x0k1.initialize(options);x7x0k1.display(); } catch (e) {}};
    var scr = d.getElementsByTagName(t)[0], par = scr.parentNode; par.insertBefore(s, scr);
    })(document, 'script');</script>

app/views/home/partners.html.haml
- title 'Partners'
.row-fluid
  .span12
    %h1 Partners
    %p 
      %b Our partners are the cornerstone of Chicago Health Atlas. 
      Initially, the Atlas was built on an existing partnership by informatics researchers at five major academic health centers in Chicago: 
      = succeed ',' do
        %a{:href => 'http://www.uic.edu/uic/'}University of Illinois at Chicago
      = succeed ',' do
        %a{:href => 'http://www.cookcountyhhs.org/locations/john-h-stroger-jr-hospital/'}Stroger Hospital
      = succeed ',' do
        %a{:href => 'http://www.uchicago.edu/'}University of Chicago
      = succeed ',' do
        %a{:href => 'http://www.northwestern.edu/'}Northwestern University
      and 
      = succeed '.' do
        %a{:href => 'http://www.rushu.rush.edu/'}Rush University
      Since that time, the Atlas has been expanded to include data and researchers from the Chicago Department of Public Health and soon, community-based organizations and other data contributing entities. The Atlas is a growing organic tool that relies heavily on partner participation and we are eager to continue this work with 
      %a{:href => 'partner_sign_up'}new partners 
      in the future.
      %hr
    %ul.partners
      %li


        %img.pull-right(src="/assets/logo_partner_chitrec.png")
        %h4 CHITREC / Feinberg School of Medicine, Northwestern University
        %h5 Dr. Abel Kho, Co-Executive Director of CHITREC
        %p
          Dr. Abel Kho is a Co-Executive Director of the Chicago Health Information Technology Regional Extension Center (CHITREC), where he contributes leadership efforts and extensive research experience in medical informatics and health information technology. A practicing physician of internal medicine at Northwestern Memorial Hospital and Northwestern Medical Faculty Foundation, he understands the significance of collecting health data to inform primary care providers, as well as epidemiologists and the public health community. Dr. Kho’s investigative team led the development of the hash algorithm and coordination of institutional partnerships for the Chicago Health Atlas.
      %li
        %img.pull-right(src="/assets/logo_partner_vanderbilt.png")
        %h4 Vanderbilt University
        %h5 Brad Malin, PhD, Privacy and Security Expert

        %p
          Early in the planning process, we recognized the need to maintain the anonymity of the patients, as well as the care providers, while retaining patient uniqueness. Dr. Malin’s expertise was critical to advise and audit the development process of re-identification risk. Dr. Malin has compared the performance of the hashing and matching software across institutions using the gold standard of an internal Enterprise Master Patient Index used for routine clinical care. He continues to audit and oversee aspects of data collection and maintenance according to HIPAA and IRB regulations.
      %li
        %img.pull-right(src="/assets/logo_partner_alliance.png")
        %h4 Alliance of Chicago Community Health Services, L3C
        %h5 Erin Kaleba, MPH, Director of Research Initiatives

        %p
          Erin Kaleba is the site investigator for the Alliance of Chicago Community Health Services. The Alliance is a network of 32 community health centers (CHCs) with more than 180 sites in 11 states with a strategic focus on health information technology and a commonly owned infrastructure through which participating CHCs can share resources to promote efficiency, quality and access.  As a key element of this infrastructure, the Alliance centrally hosts an electronic health record system. The Alliance’s Data Team has extracted data from four Alliance Health Centers to contribute to the Chicago Health Atlas.
      %li
        %img.pull-right(src="/assets/logo_partner_rush.png")
        %h4 Rush University Medical Center
        %h5 Shannon Sims, MD, PhD
        %p
          Dr. Sims is Associate Chief Medical Informatics Officer at Rush University Medical Center.  Dr. Sims’ leads the data warehouse/analytics team, clinical decision support, meaningful use, and quality measurement efforts at Rush.  Dr. Sims has extensive research experience in informatics topics including quality measurement, public health informatics, and care coordination.  He serves as the Rush site lead for the Chicago Health Atlas, where he and his investigative team contribute patient data.
      %li
        %img.pull-right(src="/assets/logo_partner_cchhs.png")
        %h4 Cook County Health & Hospital System
        %h5 Bala Hota, MD
        %p
          Dr. Hota is a practicing physician at Cook County Health & Hospitals System with extensive research experience in infectious disease epidemiology. His investigative team has contributed data to the Chicago Health Atlas project.
      %li
        %img.pull-right(src="/assets/logo_partner_uofc.png")
        %h4 University of Chicago
        %h5 David Meltzer, MD, PhD

        %p
          Dr. Meltzer is the Lead Investigator for the Chicago Health Atlas at the University of Chicago. He is a practicing physician at with a rich history of research in health economics and outcomes research in the inpatient setting. His investigative team has contributed data to the Chicago Health Atlas project.
      %li
        %img.pull-right(src="/assets/logo_partner_uofihhss.png")
        %h4 University of Illinois Hospital and Health Sciences System
        %h5 Bill Galanter, MS, MD, PhD
        %p
          Dr. Galanter is a practicing general internist at the University of Illinois Hospital & Health Sciences System (UI-Health). He has extensive research experience in clinical informatics and medication safety. He leads UI-Health’s contribution of data and analysis to the Chicago Health Atlas project.

      %li
        %img.pull-right(src="/assets/logo_partner_purple_binder.png")
        %h4 Purple Binder
        %p
          Purple Binder supplies information about local community resources to the Chicago Health Atlas, so that Chicagoans in every neighborhood can find resources near them -- everything from food pantries to childcare. A Chicago-based startup founded in 2012, Purple Binder creates datasets of community health resources so that healthcare providers can find the services their patients need in the communities where they work, live, and play.
      %li
        %img.pull-right(src="/assets/logo_partner_cdph.png")
        %h4 Chicago Department of Public Health
        %p
          One of the key initiatives of Healthy Chicago is for the Chicago Department of Public Health (CDPH) to make epidemiologic data available electronically so that Chicago’s residents, community organizations, researchers, students, and members of the media have flexibility in defining and answering questions, and engaging in public health problem-solving.  CDPH’s Epidemiology and Public Health Informatics Program collaborates in the Chicago Health Atlas by supplying public health indicator data sets via the City Data Portal and supporting efforts to visualize the data in ways that are most meaningful.

    %h3 Become a partner
    %p
      If you are a health data provider and would like to take part in this project, please view our
      %a{:href => '/partner_sign_up'} partner sign up form
      to get in touch. <b>Questions?</b> 
      %a{:href => 'mailto:kwilliams@cct.org'}Contact Kyla Williams
      of the 
      = succeed '.' do
        %a{:href => 'http://www.smartchicagocollaborative.org'}Smart Chicago Collabrative