config/routes.rb
Rails.application.routes.draw do
  apipie
  resources :uploaders do
    collection do
      get :new_health_care
      get :new_description_template
      get :health_care_indicators_index
      get :health_care_2_0_show
      get :resources
      get :resources_index
      get :new_resources
      get :indicators_map_colors
      get :indicators_map_colors_index
      get :new_indicators_map_colors
      get :description_template_index
      get :description_template_show
    end
  end
  resources :resources

  authenticated :user do
    root to: 'uploaders#index', as: :authenticated_root
  end

  root to: redirect('/users/sign_in')

  devise_for :users

  namespace :api, defaults: {format: :json} do
    namespace :v1 do

      resources :indicators, only: [:index, :show] do
      end

      resources :partners

      get '/places', to: 'geographies#index', as: 'community_areas'
      get '/place/:geo_slug', to: 'geographies#show', as: 'community_area'
      get '/place/:geo_slug/resources(/:dataset_slug)', to: 'geographies#resources_json', as: 'community_area_resources'
      get '/place/demography/:geo_slug', to: 'geographies#show_demographic_dataset', as: 'community_area_demography'
      get '/place/insurance/:cat_id/:geo_slug', to: 'geographies#show_insurance_dataset', as: 'community_area_insurance'
      get '/place/providers/:geo_slug', to: 'geographies#show_provider_dataset', as: 'community_area_provider'
      get '/place/category/:cat_id/:geo_slug', to: 'geographies#show_category_dataset', as: 'community_area_category'
      get '/topics', to: 'topics#index', as: 'topics_list'
      get '/topic_city/:year/:indicator_slug', to: 'topics#city_show', as: 'topic_city_detail'
      get '/topic_area/:year/:indicator_slug', to: 'topics#area_show', as: 'topic_community_area_detail'
      get '/topic_demo/:indicator_slug/:demo_slug', to: 'topics#demo', as: 'topic_detail_demography'
      get '/topic_detail/:indicator_slug', to: 'topics#trend', as: 'topic_detailed_all'
      get '/topic_recent/:indicator_slug', to: 'topics#recent', as: 'topic_recent'
      get '/topic_info/:geo_slug/:indicator_slug', to: 'topics#info', as: 'topic_info'
      get '/topic_sources', to: 'topics#topic_sources', as: 'topic_sources'
      get '/resources_all(/:dataset_slug)', to: 'geographies#resources_all', as: 'resources_all'
      get '/resources_category/:category_slug(/:dataset_slug)', to: 'geographies#resources_category', as: 'chicago_resources_category'
      get '/resources(/:dataset_id)/:north/:east/:south/:west' => 'geographies#resources_json'
      get '/resources(/:dataset_id)/:community_area_slug' => 'geographies#resources_json'
      get '/hospital/:slug', to: 'hospital#show', as: 'hospital_with_slug'
      get '/:geo_slug/hospitals', to: 'hospital#index', as: 'community_area_hospitals'
      get '/:geo_slug/:category_slug/community_area_detail', to: 'geographies#community_area_detail', as: 'community_area_detail'
      get '/area_indices/:indicator_slug', to: 'geographies#area_indices', as: 'area_indices'
      get '/hospitals', to: 'hospital#hospitals_all', as: 'chicago_hospitals'
      get '/race/:area_slug', to: 'topics#race', as: 'race'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>Login | Chicago Health Atlas</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'bg', media: 'all', 'data-turbolinks-track' => true %>
  <script type="text/javascrit" src="https://js.pusher.com/3.2/pusher.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

    <%= yield %>

</body>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>

</html>

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? (yield(:title) + " - Chicago Health Atlas") : "Chicago Health Atlas"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    %link{:href => "assets/favicon.ico", :rel => "shortcut icon"}/
    = stylesheet_link_tag "leaflet.css"
    = stylesheet_link_tag "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag "//fonts.googleapis.com/css?family=Raleway:400,800"
    = stylesheet_link_tag "//fonts.googleapis.com/css?family=Muli"
  %body{:class => content_for?(:title) ? (yield(:title)) : ""}
    .navbar
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Chicago Health Atlas
          
          .container.nav-collapse
            %ul.nav.pull-right
              %li{:class => current_menu_class("home")}
                %a{:href => "/"} Home
              %li{:class => current_menu_class("healthy-chicago")}
                %a{:href => "/healthy-chicago"} HEALTHY CHICAGO 2.0
              %li{:class => current_menu_class("map")}
                %a{:href => "/map"} Map
              %li{:class => current_menu_class("places")}
                %a{:href => "/places"} Places
              %li{:class => current_menu_class("hospitals")}
                %a{:href => "/hospitals"} Hospitals
              %li{:class => current_menu_class("partners")}
                %a{:href => "/partners"} Partners
              %li{:class => current_menu_class("about")}
                %a{:href => "/about"} About
  
    #container-primary.container
          
      = yield
    %footer.footer
      .container
        %p.pull-left.logomark
          Chicago Health Atlas
        %p.pull-right
          = succeed ' / ' do
            %a{:href => "http://twitter.com/smartchicago", :target => "_blank"} @smartchicago
          %a{:href => "https://github.com/smartchicago/chicago-atlas/"} Github
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    = content_for :javascripts
    = javascript_include_tag "analytics_lib" if Rails.env.production?

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Admin | Chicago Health Atlas</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <nav class="navbar navbar-default main-nav" role="navigation">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse"  data-target="#navbar-brand-centered">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-brand navbar-brand-centered">
          <a href="/">
            <%= image_tag("logo_no_bg.png") %>
          </a>
        </div>
      </div>

      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbar-brand-centered">
          <ul class="nav navbar-nav navbar-left">
            <li>
              <a href="<%= health_care_2_0_show_uploaders_path %>">Health Care 2.0</a>
            </li>
            <li>
              <a href="<%= resources_uploaders_path %>">Resources</a>
            </li>
            <li>
              <a href="<%= indicators_map_colors_uploaders_path %>">Indicators Map Colors</a>
            </li>
            <li>
              <a href="<%= description_template_show_uploaders_path %>">Description Template</a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <!-- <i class="fa fa-lg fa-user-o" aria-hidden="true"></i> -->
                <%= current_user.email %>
                <i class="fa fa-chevron-down" aria-hidden="true"></i>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to 'Edit my profile'
                  .html_safe, edit_user_registration_path, remote: true %>
                </li>
                <li>
                  <%= link_to 'Sign Out'.html_safe,
                  destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">

      <%- if notice %>
      <div class="alert alert-alert">
        <%= notice %>
      </div>
      <% end %>

      <%= yield %>
    </div>

  </body>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</html>